### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pm-mw** [sachabarber/AkkaNetDITesting#2]
Could you add a license ? Thanks :)

**Comment by sachabarber** [comment]
NOt sure where I do that. But essentially do whatever you want with it, copy it as is, change it, use it whatever

**Comment by pm-mw** [comment]
Thx for your feedback. If y want to add a license, it is quite easy. 

See https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project

**Comment by sachabarber** [comment]
done
